server:
  port: ${SERVER_PORT}
dotenv:
  enabled: true
jwt:
  secret: ${SECRET_KEY}
  token-expiration-ms: ${TOKEN_EXPIRATION_MS}
  refresh-expiration-ms: ${REFRESH_EXPIRATION_MS}
spring:
  application:
    name: First-Passport
  datasource:
    url: ${ORACLE_DB_URL}
    username: ${ORACLE_DB_USERNAME}
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: ${ORACLE_DB_USERNAME}