INSERT INTO USERS (ID, FULL_NAME, USERNAME, PASSWORD, ROLE) 
VALUES (1, 'Nguyen Hoang Bao', 'BAO', '123', 'XT');

INSERT INTO USERS (ID, FULL_NAME, USERNAME, PASSWORD, ROLE)
VALUES (2, 'Tran Thi Kim Chung', 'CHUNG', '123', 'XD');

INSERT INTO USERS (ID, FULL_NAME, USERNAME, PASSWORD, ROLE)
VALUES (3, 'Luu Thanh La', 'THANHLA', '123', 'LT');

INSERT INTO USERS (ID, FULL_NAME, USERNAME, PASSWORD, ROLE)
VALUES (4, 'Ngo Trung Hieu', 'HIEU', '123', 'GS');