INSERT INTO USERS (FULL_NAME, USERNAME, PASSWORD, ROLE)
VALUES ('Nguyen Hoang Bao', 'BAO', '$2a$12$kxLZRZupmj1jnG5cb4fCiu2sMyU6C4wEIIocCjF4PcRwMIStsd21O', 'XT');

INSERT INTO USERS (FULL_NAME, USERNAME, PASSWORD, ROLE)
VALUES ('Tran Thi Kim Chung', 'CHUNG', '$2a$12$kxLZRZupmj1jnG5cb4fCiu2sMyU6C4wEIIocCjF4PcRwMIStsd21O', 'XD');

INSERT INTO USERS (FULL_NAME, USERNAME, PASSWORD, ROLE)
VALUES ('Luu Thanh La', 'THANHLA', '$2a$12$kxLZRZupmj1jnG5cb4fCiu2sMyU6C4wEIIocCjF4PcRwMIStsd21O', 'LT');

INSERT INTO USERS (FULL_NAME, USERNAME, PASSWORD, ROLE)
VALUES ('Ngo Trung Hieu', 'HIEU', '$2a$12$kxLZRZupmj1jnG5cb4fCiu2sMyU6C4wEIIocCjF4PcRwMIStsd21O', 'GS');
