-- Run on sysdba
CREATE USER GROUP5_USER IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE TO GROUP5_USER;
GRANT CREATE SESSION TO GROUP5_USER;
GRANT CREATE TABLE TO GROUP5_USER;
GRANT CREATE VIEW TO GROUP5_USER;
GRANT CREATE SEQUENCE TO GROUP5_USER;
ALTER USER GROUP5_USER QUOTA UNLIMITED ON USERS;