-- Run on sysdba
CREATE USER GROUP5_USER IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE TO GROUP5_USER;
GRANT CREATE SESSION TO GROUP5_USER;
GRANT CREATE TABLE TO GROUP5_USER;
GRANT CREATE VIEW TO GROUP5_USER;
GRANT CREATE SEQUENCE TO GROUP5_USER;
<<<<<<< HEAD
ALTER USER GROUP5_USER QUOTA UNLIMITED ON USERS;
=======
ALTER USER GROUP5_USER QUOTA UNLIMITED ON USERS;



>>>>>>> 47d141a9737ff9dc880d116ed1736b8c7a495fb4
