-- 1. Tạo user và cấp quyền (nếu chưa có)
CREATE USER GROUP5_USER IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE TO GROUP5_USER;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO GROUP5_USER;
GRANT CREATE ANY CONTEXT TO GROUP5_USER;
GRANT EXECUTE ON DBMS_SESSION TO GROUP5_USER;
GRANT EXECUTE ON DBMS_RLS TO GROUP5_USER;
ALTER USER GROUP5_USER QUOTA UNLIMITED ON USERS;

-- 2. Tạo application context (rất quan trọng)
CREATE CONTEXT passport_ctx USING GROUP5_USER.set_passport_ctx_pkg;
