CREATE ROLE XT;
CREATE ROLE XD;
CREATE ROLE LT;
CREATE ROLE GS;

CREATE OR REPLACE VIEW group5_user.V_PASSPORT_RESULTS AS
SELECT
    ad.ID AS APPROVAL_ID,         -- ID của bản ghi phê duyệt
    ad.FORM_ID,                   -- ID của đơn đăng ký được liên kết
    ad.RESULT,                    -- Kết quả: 'APPROVED' / 'REJECTED'
    ad.APPROVED_AT,               -- Thời gian phê duyệt/từ chối
    ad.APPROVER_USER_ID,          -- ID của người đã thực hiện phê duyệt
    fr.STATUS                     -- Trạng thái cuối cùng của đơn đăng ký
FROM
    group5_user.APPROVAL_DATA ad
LEFT JOIN
    group5_user.FORM_REGISTRATION fr ON ad.FORM_ID = fr.ID;

GRANT CREATE SESSION TO XT;
GRANT SELECT, UPDATE ON group5_user.FORM_REGISTRATION TO XT;
GRANT SELECT ON group5_user.RESIDENT_DATA TO XT;

GRANT CREATE SESSION TO XD;
GRANT SELECT, UPDATE ON group5_user.FORM_REGISTRATION TO XD;
GRANT SELECT, INSERT ON group5_user.APPROVAL_DATA TO XD;

GRANT CREATE SESSION TO LT;
GRANT SELECT ON group5_user.V_PASSPORT_RESULTS TO LT;

GRANT CREATE SESSION TO GS;
GRANT SELECT ON group5_user.FORM_REGISTRATION TO GS;
GRANT SELECT ON group5_user.APPROVAL_DATA TO GS;
GRANT SELECT ON group5_user.USERS TO GS;
GRANT SELECT ON group5_user.LOGS TO GS;
GRANT SELECT ON group5_user.RESIDENT_DATA TO GS;
GRANT SELECT ON DBA_AUDIT_TRAIL TO GS;

GRANT XT, XD, GS TO GROUP5_USER;
GRANT INSERT ON group5_user.FORM_REGISTRATION TO GROUP5_USER;
GRANT INSERT ON group5_user.LOGS TO GROUP5_USER;
GRANT SELECT, UPDATE ON group5_user.USERS TO GROUP5_USER;

COMMIT;
----
ALTER SYSTEM SET AUDIT_TRAIL=DB, EXTENDED SCOPE=SPFILE;
SHUTDOWN IMMEDIATE;
STARTUP;

AUDIT SELECT, INSERT, UPDATE, DELETE ON group5_user.FORM_REGISTRATION BY ACCESS;
AUDIT SELECT, INSERT, UPDATE, DELETE ON group5_user.APPROVAL_DATA BY ACCESS;
AUDIT SELECT, INSERT, UPDATE, DELETE ON group5_user.USERS BY ACCESS;
AUDIT SELECT, INSERT, UPDATE, DELETE ON group5_user.RESIDENT_DATA BY ACCESS;

